name: Jenkins CI
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Trigger Jenkins Build
              run: |
                  curl -X POST "https://super-duper-telegram-vrrj47p54ww2xx47-8080.app.github.dev/job/test-build-stats/build?token=11b6e29d93f85392ad51d83aac0f73858c"
