name: Jenkins CI
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Trigger Jenkins Build
              run: |
                  curl -X POST "http://your-jenkins-server/job/your-job-name/build?token=YOUR_JENKINS_TOKEN"
